-- ============================================
-- Healthcare Utilization & Cost Analysis
-- Patient Population Analysis
-- ============================================
	
	
	--Gender Distribution
SELECT 
  CASE
	WHEN GENDER ='M' THEN 'M'
	WHEN GENDER ='F' THEN 'F'
	ELSE 'UNKNOWN'
	  END AS GENDER,
	  COUNT (*) AS PATIENT_COUNT,
	 ROUND(
	  COUNT (*):: NUMERIC / (SELECT COUNT (*) FROM PATIENTS) * 100, 2 ) 
	  || '%' AS PERCENTAGE_OF_PTS
FROM PATIENTS
GROUP BY GENDER
ORDER BY PATIENT_COUNT DESC;


	--Race Distribution
SELECT RACE, COUNT(*) AS PATIENT_COUNT,
	ROUND(
	  COUNT (*):: NUMERIC / (SELECT COUNT (*) FROM PATIENTS) * 100, 2 ) 
	  || '%' AS PERCENTAGE_OF_PTS
FROM PATIENTS 
GROUP BY RACE
ORDER BY PATIENT_COUNT DESC;


--Ethnicity Distribution 
SELECT ETHNICITY, COUNT(*) AS PATIENT_COUNT,
	ROUND(
		COUNT (*)::NUMERIC /(SELECT COUNT (*) FROM PATIENTS) * 100,2)
		|| '%' AS PERCENTAGE_OF_PATIENTS
FROM PATIENTS 
GROUP BY ETHNICITY
ORDER BY PATIENT_COUNT DESC;


--Age Distribution 
SELECT
	CASE
		WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, BIRTHDATE)) BETWEEN 0 AND 17
		THEN'0-17'
		WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE,BIRTHDATE)) BETWEEN 18 AND 34
		THEN '18-34'
		WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, BIRTHDATE)) BETWEEN 35 AND 49
		THEN '35-49'
		WHEN EXTRACT(YEAR FROM AGE(CURRENT_DATE, BIRTHDATE)) BETWEEN 50 AND 64
		THEN '50-64'
		ELSE '65+'
	END AS AGE_GROUP,
	COUNT(*) AS PATIENT_COUNT,
	ROUND(
		COUNT (*)::NUMERIC /(SELECT COUNT (*) FROM PATIENTS) * 100,2)
		|| '%' AS PERCENTAGE_OF_PATIENTS
	FROM PATIENTS
	GROUP BY AGE_GROUP
	ORDER BY PATIENT_COUNT DESC;


--Patient Status 
SELECT
	CASE
		WHEN DEATHDATE IS NULL THEN'LIVING'
		ELSE 'DECEASED'
	END AS PATIENT_STATUS,
	COUNT (*) AS PATIENT_COUNT,
	ROUND(
		COUNT(*)::NUMERIC /(SELECT COUNT(*) FROM PATIENTS) *100,2)
			|| '%' AS PERCENTAGE_OF_PATIENTS
	FROM PATIENTS
	GROUP BY PATIENT_STATUS
	ORDER BY PATIENT_COUNT DESC;


--Patient Income Distribution
SELECT 
	MIN(INCOME)AS MIN_INCOME,
	MAX(INCOME)AS MAX_INCOME,
	ROUND(AVG(INCOME),2) AS AVG_INCOME,
	PERCENTILE_CONT(0.5)
		WITHIN GROUP(ORDER BY INCOME) AS MEDIAN_INCOME
	FROM PATIENTS;


--Patient Health Coverage Distribution
SELECT 
	MIN(HEALTHCARE_COVERAGE)AS MIN_COVERAGE,
	MAX(HEALTHCARE_COVERAGE)AS MAX_COVERAGE,
	ROUND(AVG(HEALTHCARE_COVERAGE),2) AS AVG_COVERAGE,
	PERCENTILE_CONT(0.5)
		WITHIN GROUP(ORDER BY HEALTHCARE_COVERAGE) AS MEDIAN_COVERAGE
	FROM PATIENTS;


--Income vs. Coverage Correlation (Negligible)
SELECT 
	ROUND(
		CORR(INCOME,HEALTHCARE_COVERAGE)::NUMERIC,3
	)AS INCOME_COVERAGE_CORRELATION
FROM PATIENTS;
